export const MEETING_DATA = 'meeting_data'
export const USER_JOINED = 'user_joined'
export const USER_LEFT = 'user_left'
export const SEND_MESSAGE = 'send_message'
export const MESSAGE_DATA = 'message_data'
export const ORGANISER_LEFT = 'organiser_left'
export const RECORDING_STARTED = 'user_recrd_start'
export const RECORDING_STOPPED = 'user_recrd_stop'

// VIDEO CALL MESSAGES
export const ALL_USERS = 'all_users'
// export const USER_JOINED = 'user_joined'
export const HEY = 'hey'
export const CALL_ACCEPTED = 'call_accepted'
export const USER_TURNED_OFF_VIDEO = 'user_turned_off_video'
