export const MEETING_DATA = 'meeting_data'
export const USER_JOINED = 'user_joined'
export const USER_LEFT = 'user_left'
export const SEND_MESSAGE = 'send_message'
export const MESSAGE_DATA = 'message_data'