export const MEETING_DATA = 'meeting_data'
export const USER_JOINED = 'user_joined'
export const USER_LEFT = 'user_left'
export const SEND_MESSAGE = 'send_message'
export const MESSAGE_DATA = 'message_data'
export const ORGANISER_LEFT = 'organiser_left'
export const RECORDING_STARTED = 'user_recrd_start'
export const RECORDING_STOPPED = 'user_recrd_stop'
